import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');
const TIMELINE_WIDTH = 25;
const CARD_MARGIN = 20;
const CARD_WIDTH = width - TIMELINE_WIDTH - CARD_MARGIN * 2;
const CARD_HEIGHT = height * 0.8;

export const TripTimelineStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
    paddingTop: 0,
  },
  animatedBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
    zIndex: 0,
  },
  animatedGradient1: {
    position: 'absolute',
    top: -100,
    right: -100,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: '#6366f1',
    opacity: 0.1,
  },
  animatedGradient2: {
    position: 'absolute',
    bottom: -150,
    left: -150,
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: '#8b5cf6',
    opacity: 0.08,
  },
  animatedBubble1: {
    position: 'absolute',
    top: '5%',
    right: '5%',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#a855f7',
    opacity: 0.1,
  },
  animatedBubble2: {
    position: 'absolute',
    bottom: '5%',
    left: '5%',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#ec4899',
    opacity: 0.08,
  },
  animatedBubble3: {
    position: 'absolute',
    top: '5%',
    left: '5%',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#f59e0b',
    opacity: 0.12,
  },
  animatedBubble4: {
    position: 'absolute',
    bottom: '5%',
    right: '5%',
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#10b981',
    opacity: 0.09,
  },
  animatedBubble5: {
    position: 'absolute',
    top: '50%',
    left: '2%',
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#3b82f6',
    opacity: 0.11,
  },
  mainContent: {
    flex: 1,
    position: 'relative',
    marginTop: 0,
    paddingTop: 0,
  },
  timelineContainer: {
    width: 15,
    backgroundColor: 'transparent',
    position: 'absolute',
    left: 10,
    top: 15,
    bottom: 15,
    zIndex: 15,
  },
  timelineLine: {
    position: 'absolute',
    left: 17,
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: '#e2e8f0',
    zIndex: 0,
  },
  timelineContent: {
    position: 'relative',
    height: '100%',
  },
  timelineDotContainer: {
    position: 'absolute',
    left: 1,
    width: 50,
    height: 80,
    zIndex: 20,
  },
  timelineDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#fff',
    borderWidth: 3,
    borderColor: '#cbd5e1',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  timelineDotActive: {
    backgroundColor: '#6366f1',
    borderColor: '#6366f1',
    shadowColor: '#6366f1',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 6,
  },
  timelineDotText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#64748b',
  },
  timelineDotTextActive: {
    color: '#fff',
    fontWeight: 'bold',
  },
  timelineLabel: {
    fontSize: 7,
    color: '#64748b',
    fontWeight: '500',
    textAlign: 'center',
    width: 35,
    position: 'absolute',
    top: 40,
    left: 0,
  },
  timelineLabelActive: {
    color: '#1e293b',
    fontWeight: 'bold',
  },
  carouselContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingLeft: TIMELINE_WIDTH + CARD_MARGIN,
    paddingTop: 15,
    paddingBottom: 15,
    zIndex: 10,
  },
  carouselContent: {
    alignItems: 'center',
    paddingBottom: 20,
  },
  cardWrapper: {
    width: '100%',
    height: '100%',
    zIndex: 10,
    borderRadius: 0,
    overflow: 'hidden',
  },
  dayCard: {
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    backgroundColor: 'transparent',
    borderRadius: 0,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
    borderWidth: 0,
  },
  dayHeader: {
    marginTop: 16,
    alignItems: 'center',
  },
  dayTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1e293b',
    textAlign: 'center',
    textShadowColor: 'rgba(255,255,255,0.8)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  dayTitleContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(99, 102, 241, 0.3)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  activitiesContainer: {
    flex: 1,
    marginBottom: 12,
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  activityIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f1f5f9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  activityDetails: {
    flex: 1,
  },
  activityTime: {
    fontSize: 16,
    color: '#374151',
    marginBottom: 4,
    fontWeight: '600',
  },
  activityTitle: {
    fontSize: 18,
    color: '#111827',
    fontWeight: 'bold',
  },
  summaryCard: {
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.3)',
  },
  summaryText: {
    color: '#1e293b',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  timelineLabelParis: {
    color: '#2563eb',
  },
  timelineDotParis: {
    borderColor: '#2563eb',
    backgroundColor: '#e0e7ff',
  },
  timelineLabelNice: {
    color: '#a21caf',
  },
  timelineDotNice: {
    borderColor: '#a21caf',
    backgroundColor: '#f3e8ff',
  },
  timelineLabelDeparture: {
    color: '#64748b',
    fontWeight: 'bold',
  },
  timelineDotDeparture: {
    borderColor: '#64748b',
    backgroundColor: '#f1f5f9',
    borderStyle: 'dashed',
  },
  timelineDotEmoji: {
    fontSize: 20,
    textAlign: 'center',
  },
  cardBgImage: {
    flex: 1,
    width: '100%',
    height: '100%',
    borderRadius: 0,
    overflow: 'hidden',
  },
  cardBgOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.6)',
  },
  // Drawer Styles
  drawerContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
  },
  drawerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000',
  },
  drawerContent: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: width * 0.85,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: -2, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  drawerHandle: {
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  drawerHandleBar: {
    width: 40,
    height: 4,
    backgroundColor: '#d1d5db',
    borderRadius: 2,
  },
  drawerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  drawerHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  drawerHeaderIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f1f5f9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  drawerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1e293b',
    flex: 1,
  },
  drawerCloseButton: {
    padding: 4,
  },
  drawerBody: {
    flex: 1,
    padding: 20,
  },
  drawerInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  drawerInfoText: {
    fontSize: 16,
    color: '#374151',
    marginLeft: 8,
    flex: 1,
  },
  drawerSection: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  drawerSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 12,
  },
  drawerNotes: {
    fontSize: 16,
    color: '#6b7280',
    lineHeight: 24,
  },
  drawerLinkButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  drawerLinkButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
  // Modal Styles (keeping for backward compatibility)
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 16,
    width: '90%',
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  modalHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  modalHeaderIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f1f5f9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1e293b',
    flex: 1,
  },
  closeButton: {
    padding: 4,
  },
  modalBody: {
    padding: 20,
  },
  modalInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  modalInfoText: {
    fontSize: 16,
    color: '#374151',
    marginLeft: 8,
    flex: 1,
  },
  modalSection: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  modalSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 12,
  },
  modalNotes: {
    fontSize: 16,
    color: '#6b7280',
    lineHeight: 24,
  },
  linkButton: {
    backgroundColor: '#6366f1',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  linkButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 8,
  },
});

export { CARD_WIDTH, CARD_HEIGHT, TIMELINE_WIDTH, CARD_MARGIN }; 